<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Messages_Model_Base_MessageCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'message_id',
        'created' => 'message_created',
        'updated' => 'message_updated',
        'fromTo' => 'message_from_to',
        'title' => 'message_title',
        'body' => 'message_body',
        'bodyHtml' => 'message_body_html',
        'bodyFilterId' => 'message_body_filter_id',
        'read' => 'message_read',
        'star' => 'message_star',
        'deleted' => 'message_deleted',
        'type' => 'message_type',
        'key' => 'message_key',
        'userId' => 'message_user_id',
    );
}