<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
pluginsy/Messages/Model/MessageGateway.php
*/
abstract class Plugg_Messages_Model_Base_MessageGateway extends Sabai_Model_Gateway
{
    public function getName()
    {
        return 'message';
    }

    public function getFields()
    {
        return array('message_id' => Sabai_Model::KEY_TYPE_INT, 'message_created' => Sabai_Model::KEY_TYPE_INT, 'message_updated' => Sabai_Model::KEY_TYPE_INT, 'message_from_to' => Sabai_Model::KEY_TYPE_INT, 'message_title' => Sabai_Model::KEY_TYPE_VARCHAR, 'message_body' => Sabai_Model::KEY_TYPE_TEXT, 'message_body_html' => Sabai_Model::KEY_TYPE_TEXT, 'message_body_filter_id' => Sabai_Model::KEY_TYPE_INT, 'message_read' => Sabai_Model::KEY_TYPE_INT, 'message_star' => Sabai_Model::KEY_TYPE_INT, 'message_deleted' => Sabai_Model::KEY_TYPE_INT, 'message_type' => Sabai_Model::KEY_TYPE_INT, 'message_key' => Sabai_Model::KEY_TYPE_VARCHAR, 'message_user_id' => Sabai_Model::KEY_TYPE_INT);
    }

    protected function _getSelectByIdQuery($id, $fields)
    {
        return sprintf(
            'SELECT %s FROM %smessage WHERE message_id = %d',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $id
        );
    }

    protected function _getSelectByIdsQuery($ids, $fields)
    {
        return sprintf(
            'SELECT %s FROM %smessage WHERE message_id IN (%s)',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            implode(',', array_map('intval', $ids))
        );
    }

    protected function _getSelectByCriteriaQuery($criteriaStr, $fields)
    {
        return sprintf(
            'SELECT %1$s FROM %2$smessage WHERE %3$s',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $criteriaStr
        );
    }

    protected function _getInsertQuery($values)
    {
        $values['message_created'] = time();
        $values['message_updated'] = 0;
        return sprintf("INSERT INTO %smessage(message_created, message_updated, message_from_to, message_title, message_body, message_body_html, message_body_filter_id, message_read, message_star, message_deleted, message_type, message_key, message_user_id) VALUES(%d, %d, %d, %s, %s, %s, %d, %d, %d, %d, %d, %s, %d)", $this->_db->getResourcePrefix(), $values['message_created'], $values['message_updated'], $values['message_from_to'], $this->_db->escapeString($values['message_title']), $this->_db->escapeString($values['message_body']), $this->_db->escapeString($values['message_body_html']), $values['message_body_filter_id'], $values['message_read'], $values['message_star'], $values['message_deleted'], $values['message_type'], $this->_db->escapeString($values['message_key']), $values['message_user_id']);
    }

    protected function _getUpdateQuery($id, $values)
    {
        $last_update = $values['message_updated'];
        $values['message_updated'] = time();
        return sprintf("UPDATE %smessage SET message_updated = %d, message_from_to = %d, message_title = %s, message_body = %s, message_body_html = %s, message_body_filter_id = %d, message_read = %d, message_star = %d, message_deleted = %d, message_type = %d, message_key = %s, message_user_id = %d WHERE message_id = %d AND message_updated = %d", $this->_db->getResourcePrefix(), $values['message_updated'], $values['message_from_to'], $this->_db->escapeString($values['message_title']), $this->_db->escapeString($values['message_body']), $this->_db->escapeString($values['message_body_html']), $values['message_body_filter_id'], $values['message_read'], $values['message_star'], $values['message_deleted'], $values['message_type'], $this->_db->escapeString($values['message_key']), $values['message_user_id'], $id, $last_update);
    }

    protected function _getDeleteQuery($id)
    {
        return sprintf('DELETE FROM %1$smessage WHERE message_id = %2$d', $this->_db->getResourcePrefix(), $id);
    }

    protected function _getUpdateByCriteriaQuery($criteriaStr, $sets)
    {
        $sets['message_updated'] = 'message_updated=' . time();
        return sprintf('UPDATE %smessage SET %s WHERE %s', $this->_db->getResourcePrefix(), implode(',', $sets), $criteriaStr);
    }

    protected function _getDeleteByCriteriaQuery($criteriaStr)
    {
        return sprintf('DELETE FROM %1$smessage WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    protected function _getCountByCriteriaQuery($criteriaStr)
    {
        return sprintf('SELECT COUNT(*) FROM %1$smessage WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }
}