<?php
class Plugg_Widgets_Model_Activewidget extends Plugg_Widgets_Model_Base_Activewidget{
}

class Plugg_Widgets_Model_ActivewidgetRepository extends Plugg_Widgets_Model_Base_ActivewidgetRepository
{
}