<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Uploads_Model_Base_FileCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'file_id',
        'created' => 'file_created',
        'updated' => 'file_updated',
        'name' => 'file_name',
        'fileName' => 'file_file_name',
        'type' => 'file_type',
        'size' => 'file_size',
        'isImage' => 'file_is_image',
        'imageWidth' => 'file_image_width',
        'imageHeight' => 'file_image_height',
        'thumbnail' => 'file_thumbnail',
        'thumbnailWidth' => 'file_thumbnail_width',
        'thumbnailHeight' => 'file_thumbnail_height',
        'protected' => 'file_protected',
        'userId' => 'file_user_id',
        'groupId' => 'file_group_id',
    );
}