<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Forum_Model_Base_AttachmentCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'attachment_id',
        'created' => 'attachment_created',
        'updated' => 'attachment_updated',
        'fileId' => 'attachment_file_id',
        'topicId' => 'attachment_topic_id',
        'commentId' => 'attachment_comment_id',
    );
}