<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Forum_Model_Base_CommentCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'comment_id',
        'created' => 'comment_created',
        'updated' => 'comment_updated',
        'title' => 'comment_title',
        'body' => 'comment_body',
        'bodyHtml' => 'comment_body_html',
        'bodyFilterId' => 'comment_body_filter_id',
        'ip' => 'comment_ip',
        'host' => 'comment_host',
        'parentId' => 'comment_parent_id',
        'topicId' => 'comment_topic_id',
        'parent' => 'comment_parent',
        'userId' => 'comment_user_id',
        'starCount' => 'comment_star_count',
        'starLast' => 'comment_star_last',
        'starLasttime' => 'comment_star_lasttime',
        'attachmentCount' => 'comment_attachment_count',
        'attachmentLast' => 'comment_attachment_last',
        'attachmentLasttime' => 'comment_attachment_lasttime',
    );
}