<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Forum_Model_Base_TopicCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'topic_id',
        'created' => 'topic_created',
        'updated' => 'topic_updated',
        'title' => 'topic_title',
        'body' => 'topic_body',
        'bodyHtml' => 'topic_body_html',
        'bodyFilterId' => 'topic_body_filter_id',
        'ip' => 'topic_ip',
        'host' => 'topic_host',
        'closed' => 'topic_closed',
        'sticky' => 'topic_sticky',
        'views' => 'topic_views',
        'lastPosted' => 'topic_last_posted',
        'userId' => 'topic_user_id',
        'groupId' => 'topic_group_id',
        'commentCount' => 'topic_comment_count',
        'commentLast' => 'topic_comment_last',
        'commentLasttime' => 'topic_comment_lasttime',
        'starCount' => 'topic_star_count',
        'starLast' => 'topic_star_last',
        'starLasttime' => 'topic_star_lasttime',
        'attachmentCount' => 'topic_attachment_count',
        'attachmentLast' => 'topic_attachment_last',
        'attachmentLasttime' => 'topic_attachment_lasttime',
    );
}