<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Forum_Model_Base_ViewCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'view_id',
        'created' => 'view_created',
        'updated' => 'view_updated',
        'lastViewed' => 'view_last_viewed',
        'topicId' => 'view_topic_id',
        'userId' => 'view_user_id',
    );
}