<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
plugins/System/Model/Adminroute.php
*/
abstract class Plugg_System_Model_Base_Adminroute extends Sabai_Model_Entity
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Adminroute', $model);
        $this->_vars = array('adminroute_id' => 0, 'adminroute_created' => 0, 'adminroute_updated' => 0, 'adminroute_path' => null, 'adminroute_format' => null, 'adminroute_controller' => null, 'adminroute_forward' => null, 'adminroute_plugin' => null, 'adminroute_type' => 0, 'adminroute_access_callback' => 0, 'adminroute_title_callback' => 0, 'adminroute_title' => null, 'adminroute_weight' => 0, 'adminroute_depth' => 0);
    }

    public function __clone()
    {
        $this->_vars = array_merge($this->_vars, array('adminroute_id' => 0, 'adminroute_created' => 0, 'adminroute_updated' => 0));
    }

    public function __toString()
    {
        return $this->_get('path', null, null);
    }

    protected function _get($name, $sort, $order, $limit = 0, $offset = 0)
    {
        switch ($name) {
        case 'id':
            return $this->_vars['adminroute_id'];
        case 'created':
            return $this->_vars['adminroute_created'];
        case 'updated':
            return $this->_vars['adminroute_updated'];
        case 'path':
            return $this->_vars['adminroute_path'];
        case 'format':
            return $this->_vars['adminroute_format'];
        case 'controller':
            return $this->_vars['adminroute_controller'];
        case 'forward':
            return $this->_vars['adminroute_forward'];
        case 'plugin':
            return $this->_vars['adminroute_plugin'];
        case 'type':
            return $this->_vars['adminroute_type'];
        case 'access_callback':
            return $this->_vars['adminroute_access_callback'];
        case 'title_callback':
            return $this->_vars['adminroute_title_callback'];
        case 'title':
            return $this->_vars['adminroute_title'];
        case 'weight':
            return $this->_vars['adminroute_weight'];
        case 'depth':
            return $this->_vars['adminroute_depth'];
default:
return isset($this->_objects[$name]) ? $this->_objects[$name] : null;
        }
    }

    protected function _set($name, $value, $markDirty)
    {
        switch ($name) {
        case 'id':
            $this->_setVar('adminroute_id', $value, $markDirty);
            break;
        case 'path':
            $this->_setVar('adminroute_path', $value, $markDirty);
            break;
        case 'format':
            $this->_setVar('adminroute_format', $value, $markDirty);
            break;
        case 'controller':
            $this->_setVar('adminroute_controller', $value, $markDirty);
            break;
        case 'forward':
            $this->_setVar('adminroute_forward', $value, $markDirty);
            break;
        case 'plugin':
            $this->_setVar('adminroute_plugin', $value, $markDirty);
            break;
        case 'type':
            $this->_setVar('adminroute_type', $value, $markDirty);
            break;
        case 'access_callback':
            $this->_setVar('adminroute_access_callback', $value, $markDirty);
            break;
        case 'title_callback':
            $this->_setVar('adminroute_title_callback', $value, $markDirty);
            break;
        case 'title':
            $this->_setVar('adminroute_title', $value, $markDirty);
            break;
        case 'weight':
            $this->_setVar('adminroute_weight', $value, $markDirty);
            break;
        case 'depth':
            $this->_setVar('adminroute_depth', $value, $markDirty);
            break;
        }
    }

    protected function _initVar($name, $value)
    {
        switch ($name) {
        default:
            $this->_vars[$name] = $value;
            break;
        }
    }
}

abstract class Plugg_System_Model_Base_AdminrouteRepository extends Sabai_Model_EntityRepository
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Adminroute', $model);
    }

    protected function _getCollectionByRowset(Sabai_DB_Rowset $rs)
    {
        return new Plugg_System_Model_Base_AdminroutesByRowset($rs, $this->_model->create('Adminroute'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Plugg_System_Model_Base_Adminroutes($this->_model, $entities);
    }
}

class Plugg_System_Model_Base_AdminroutesByRowset extends Sabai_Model_EntityCollection_Rowset
{
    public function __construct(Sabai_DB_Rowset $rs, Plugg_System_Model_Adminroute $emptyEntity, Sabai_Model $model)
    {
        parent::__construct('Adminroutes', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(Sabai_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Plugg_System_Model_Base_Adminroutes extends Sabai_Model_EntityCollection_Array
{
    public function __construct(Sabai_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Adminroutes', $entities);
    }
}