<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_System_Model_Base_AdminrouteCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'adminroute_id',
        'created' => 'adminroute_created',
        'updated' => 'adminroute_updated',
        'path' => 'adminroute_path',
        'format' => 'adminroute_format',
        'controller' => 'adminroute_controller',
        'forward' => 'adminroute_forward',
        'plugin' => 'adminroute_plugin',
        'type' => 'adminroute_type',
        'accessCallback' => 'adminroute_access_callback',
        'titleCallback' => 'adminroute_title_callback',
        'title' => 'adminroute_title',
        'weight' => 'adminroute_weight',
        'depth' => 'adminroute_depth',
    );
}