<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_System_Model_Base_DependencyCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'dependency_id',
        'created' => 'dependency_created',
        'updated' => 'dependency_updated',
        'requires' => 'dependency_requires',
        'pluginId' => 'dependency_plugin_id',
    );
}