<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_System_Model_Base_PluginCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'plugin_id',
        'created' => 'plugin_created',
        'updated' => 'plugin_updated',
        'name' => 'plugin_name',
        'nicename' => 'plugin_nicename',
        'version' => 'plugin_version',
        'params' => 'plugin_params',
        'priority' => 'plugin_priority',
        'active' => 'plugin_active',
        'locked' => 'plugin_locked',
    );
}