<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
plugins/System/Model/Route.php
*/
abstract class Plugg_System_Model_Base_Route extends Sabai_Model_Entity
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Route', $model);
        $this->_vars = array('route_id' => 0, 'route_created' => 0, 'route_updated' => 0, 'route_path' => null, 'route_format' => null, 'route_controller' => null, 'route_forward' => null, 'route_plugin' => null, 'route_type' => 0, 'route_access_callback' => 0, 'route_title_callback' => 0, 'route_title' => null, 'route_weight' => 0, 'route_depth' => 0);
    }

    public function __clone()
    {
        $this->_vars = array_merge($this->_vars, array('route_id' => 0, 'route_created' => 0, 'route_updated' => 0));
    }

    public function __toString()
    {
        return $this->_get('path', null, null);
    }

    protected function _get($name, $sort, $order, $limit = 0, $offset = 0)
    {
        switch ($name) {
        case 'id':
            return $this->_vars['route_id'];
        case 'created':
            return $this->_vars['route_created'];
        case 'updated':
            return $this->_vars['route_updated'];
        case 'path':
            return $this->_vars['route_path'];
        case 'format':
            return $this->_vars['route_format'];
        case 'controller':
            return $this->_vars['route_controller'];
        case 'forward':
            return $this->_vars['route_forward'];
        case 'plugin':
            return $this->_vars['route_plugin'];
        case 'type':
            return $this->_vars['route_type'];
        case 'access_callback':
            return $this->_vars['route_access_callback'];
        case 'title_callback':
            return $this->_vars['route_title_callback'];
        case 'title':
            return $this->_vars['route_title'];
        case 'weight':
            return $this->_vars['route_weight'];
        case 'depth':
            return $this->_vars['route_depth'];
default:
return isset($this->_objects[$name]) ? $this->_objects[$name] : null;
        }
    }

    protected function _set($name, $value, $markDirty)
    {
        switch ($name) {
        case 'id':
            $this->_setVar('route_id', $value, $markDirty);
            break;
        case 'path':
            $this->_setVar('route_path', $value, $markDirty);
            break;
        case 'format':
            $this->_setVar('route_format', $value, $markDirty);
            break;
        case 'controller':
            $this->_setVar('route_controller', $value, $markDirty);
            break;
        case 'forward':
            $this->_setVar('route_forward', $value, $markDirty);
            break;
        case 'plugin':
            $this->_setVar('route_plugin', $value, $markDirty);
            break;
        case 'type':
            $this->_setVar('route_type', $value, $markDirty);
            break;
        case 'access_callback':
            $this->_setVar('route_access_callback', $value, $markDirty);
            break;
        case 'title_callback':
            $this->_setVar('route_title_callback', $value, $markDirty);
            break;
        case 'title':
            $this->_setVar('route_title', $value, $markDirty);
            break;
        case 'weight':
            $this->_setVar('route_weight', $value, $markDirty);
            break;
        case 'depth':
            $this->_setVar('route_depth', $value, $markDirty);
            break;
        }
    }

    protected function _initVar($name, $value)
    {
        switch ($name) {
        default:
            $this->_vars[$name] = $value;
            break;
        }
    }
}

abstract class Plugg_System_Model_Base_RouteRepository extends Sabai_Model_EntityRepository
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Route', $model);
    }

    protected function _getCollectionByRowset(Sabai_DB_Rowset $rs)
    {
        return new Plugg_System_Model_Base_RoutesByRowset($rs, $this->_model->create('Route'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Plugg_System_Model_Base_Routes($this->_model, $entities);
    }
}

class Plugg_System_Model_Base_RoutesByRowset extends Sabai_Model_EntityCollection_Rowset
{
    public function __construct(Sabai_DB_Rowset $rs, Plugg_System_Model_Route $emptyEntity, Sabai_Model $model)
    {
        parent::__construct('Routes', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(Sabai_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Plugg_System_Model_Base_Routes extends Sabai_Model_EntityCollection_Array
{
    public function __construct(Sabai_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Routes', $entities);
    }
}