<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_System_Model_Base_RouteCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'route_id',
        'created' => 'route_created',
        'updated' => 'route_updated',
        'path' => 'route_path',
        'format' => 'route_format',
        'controller' => 'route_controller',
        'forward' => 'route_forward',
        'plugin' => 'route_plugin',
        'type' => 'route_type',
        'accessCallback' => 'route_access_callback',
        'titleCallback' => 'route_title_callback',
        'title' => 'route_title',
        'weight' => 'route_weight',
        'depth' => 'route_depth',
    );
}