<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
pluginsy/System/Model/RouteGateway.php
*/
abstract class Plugg_System_Model_Base_RouteGateway extends Sabai_Model_Gateway
{
    public function getName()
    {
        return 'route';
    }

    public function getFields()
    {
        return array('route_id' => Sabai_Model::KEY_TYPE_INT, 'route_created' => Sabai_Model::KEY_TYPE_INT, 'route_updated' => Sabai_Model::KEY_TYPE_INT, 'route_path' => Sabai_Model::KEY_TYPE_VARCHAR, 'route_format' => Sabai_Model::KEY_TYPE_TEXT, 'route_controller' => Sabai_Model::KEY_TYPE_VARCHAR, 'route_forward' => Sabai_Model::KEY_TYPE_VARCHAR, 'route_plugin' => Sabai_Model::KEY_TYPE_VARCHAR, 'route_type' => Sabai_Model::KEY_TYPE_INT, 'route_access_callback' => Sabai_Model::KEY_TYPE_INT, 'route_title_callback' => Sabai_Model::KEY_TYPE_INT, 'route_title' => Sabai_Model::KEY_TYPE_VARCHAR, 'route_weight' => Sabai_Model::KEY_TYPE_INT, 'route_depth' => Sabai_Model::KEY_TYPE_INT);
    }

    protected function _getSelectByIdQuery($id, $fields)
    {
        return sprintf(
            'SELECT %s FROM %sroute WHERE route_id = %d',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $id
        );
    }

    protected function _getSelectByIdsQuery($ids, $fields)
    {
        return sprintf(
            'SELECT %s FROM %sroute WHERE route_id IN (%s)',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            implode(',', array_map('intval', $ids))
        );
    }

    protected function _getSelectByCriteriaQuery($criteriaStr, $fields)
    {
        return sprintf(
            'SELECT %1$s FROM %2$sroute WHERE %3$s',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $criteriaStr
        );
    }

    protected function _getInsertQuery($values)
    {
        $values['route_created'] = time();
        $values['route_updated'] = 0;
        return sprintf("INSERT INTO %sroute(route_created, route_updated, route_path, route_format, route_controller, route_forward, route_plugin, route_type, route_access_callback, route_title_callback, route_title, route_weight, route_depth) VALUES(%d, %d, %s, %s, %s, %s, %s, %d, %d, %d, %s, %d, %d)", $this->_db->getResourcePrefix(), $values['route_created'], $values['route_updated'], $this->_db->escapeString($values['route_path']), $this->_db->escapeString($values['route_format']), $this->_db->escapeString($values['route_controller']), $this->_db->escapeString($values['route_forward']), $this->_db->escapeString($values['route_plugin']), $values['route_type'], $values['route_access_callback'], $values['route_title_callback'], $this->_db->escapeString($values['route_title']), $values['route_weight'], $values['route_depth']);
    }

    protected function _getUpdateQuery($id, $values)
    {
        $last_update = $values['route_updated'];
        $values['route_updated'] = time();
        return sprintf("UPDATE %sroute SET route_updated = %d, route_path = %s, route_format = %s, route_controller = %s, route_forward = %s, route_plugin = %s, route_type = %d, route_access_callback = %d, route_title_callback = %d, route_title = %s, route_weight = %d, route_depth = %d WHERE route_id = %d AND route_updated = %d", $this->_db->getResourcePrefix(), $values['route_updated'], $this->_db->escapeString($values['route_path']), $this->_db->escapeString($values['route_format']), $this->_db->escapeString($values['route_controller']), $this->_db->escapeString($values['route_forward']), $this->_db->escapeString($values['route_plugin']), $values['route_type'], $values['route_access_callback'], $values['route_title_callback'], $this->_db->escapeString($values['route_title']), $values['route_weight'], $values['route_depth'], $id, $last_update);
    }

    protected function _getDeleteQuery($id)
    {
        return sprintf('DELETE FROM %1$sroute WHERE route_id = %2$d', $this->_db->getResourcePrefix(), $id);
    }

    protected function _getUpdateByCriteriaQuery($criteriaStr, $sets)
    {
        $sets['route_updated'] = 'route_updated=' . time();
        return sprintf('UPDATE %sroute SET %s WHERE %s', $this->_db->getResourcePrefix(), implode(',', $sets), $criteriaStr);
    }

    protected function _getDeleteByCriteriaQuery($criteriaStr)
    {
        return sprintf('DELETE FROM %1$sroute WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    protected function _getCountByCriteriaQuery($criteriaStr)
    {
        return sprintf('SELECT COUNT(*) FROM %1$sroute WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }
}