<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
pluginsy/Footprints/Model/FootprintGateway.php
*/
abstract class Plugg_Footprints_Model_Base_FootprintGateway extends Sabai_Model_Gateway
{
    public function getName()
    {
        return 'footprint';
    }

    public function getFields()
    {
        return array('footprint_id' => Sabai_Model::KEY_TYPE_INT, 'footprint_created' => Sabai_Model::KEY_TYPE_INT, 'footprint_updated' => Sabai_Model::KEY_TYPE_INT, 'footprint_target' => Sabai_Model::KEY_TYPE_VARCHAR, 'footprint_timestamp' => Sabai_Model::KEY_TYPE_INT, 'footprint_hidden' => Sabai_Model::KEY_TYPE_INT, 'footprint_user_id' => Sabai_Model::KEY_TYPE_INT);
    }

    protected function _getSelectByIdQuery($id, $fields)
    {
        return sprintf(
            'SELECT %s FROM %sfootprint WHERE footprint_id = %d',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $id
        );
    }

    protected function _getSelectByIdsQuery($ids, $fields)
    {
        return sprintf(
            'SELECT %s FROM %sfootprint WHERE footprint_id IN (%s)',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            implode(',', array_map('intval', $ids))
        );
    }

    protected function _getSelectByCriteriaQuery($criteriaStr, $fields)
    {
        return sprintf(
            'SELECT %1$s FROM %2$sfootprint WHERE %3$s',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $criteriaStr
        );
    }

    protected function _getInsertQuery($values)
    {
        $values['footprint_created'] = time();
        $values['footprint_updated'] = 0;
        return sprintf("INSERT INTO %sfootprint(footprint_created, footprint_updated, footprint_target, footprint_timestamp, footprint_hidden, footprint_user_id) VALUES(%d, %d, %s, %d, %d, %d)", $this->_db->getResourcePrefix(), $values['footprint_created'], $values['footprint_updated'], $this->_db->escapeString($values['footprint_target']), $values['footprint_timestamp'], $values['footprint_hidden'], $values['footprint_user_id']);
    }

    protected function _getUpdateQuery($id, $values)
    {
        $last_update = $values['footprint_updated'];
        $values['footprint_updated'] = time();
        return sprintf("UPDATE %sfootprint SET footprint_updated = %d, footprint_target = %s, footprint_timestamp = %d, footprint_hidden = %d, footprint_user_id = %d WHERE footprint_id = %d AND footprint_updated = %d", $this->_db->getResourcePrefix(), $values['footprint_updated'], $this->_db->escapeString($values['footprint_target']), $values['footprint_timestamp'], $values['footprint_hidden'], $values['footprint_user_id'], $id, $last_update);
    }

    protected function _getDeleteQuery($id)
    {
        return sprintf('DELETE FROM %1$sfootprint WHERE footprint_id = %2$d', $this->_db->getResourcePrefix(), $id);
    }

    protected function _getUpdateByCriteriaQuery($criteriaStr, $sets)
    {
        $sets['footprint_updated'] = 'footprint_updated=' . time();
        return sprintf('UPDATE %sfootprint SET %s WHERE %s', $this->_db->getResourcePrefix(), implode(',', $sets), $criteriaStr);
    }

    protected function _getDeleteByCriteriaQuery($criteriaStr)
    {
        return sprintf('DELETE FROM %1$sfootprint WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    protected function _getCountByCriteriaQuery($criteriaStr)
    {
        return sprintf('SELECT COUNT(*) FROM %1$sfootprint WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }
}