<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Footprints_Model_Base_FootprintCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'footprint_id',
        'created' => 'footprint_created',
        'updated' => 'footprint_updated',
        'target' => 'footprint_target',
        'timestamp' => 'footprint_timestamp',
        'hidden' => 'footprint_hidden',
        'userId' => 'footprint_user_id',
    );
}