<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
plugins/SimpleSearch/Model/Text.php
*/
abstract class Plugg_SimpleSearch_Model_Base_Text extends Sabai_Model_Entity
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Text', $model);
        $this->_vars = array('text_id' => 0, 'text_created' => 0, 'text_updated' => 0, 'text_content_id' => 0, 'text_ctime' => 0, 'text_mtime' => 0, 'text_title' => null, 'text_body' => null, 'text_author_id' => 0, 'text_searchable_id' => 0, 'text_content_group' => null, 'text_plugin' => null);
    }

    public function __clone()
    {
        $this->_vars = array_merge($this->_vars, array('text_id' => 0, 'text_created' => 0, 'text_updated' => 0));
    }

    public function __toString()
    {
        return 'Text #' . $this->_get('id', null, null);
    }

    protected function _get($name, $sort, $order, $limit = 0, $offset = 0)
    {
        switch ($name) {
        case 'id':
            return $this->_vars['text_id'];
        case 'created':
            return $this->_vars['text_created'];
        case 'updated':
            return $this->_vars['text_updated'];
        case 'content_id':
            return $this->_vars['text_content_id'];
        case 'ctime':
            return $this->_vars['text_ctime'];
        case 'mtime':
            return $this->_vars['text_mtime'];
        case 'title':
            return $this->_vars['text_title'];
        case 'body':
            return $this->_vars['text_body'];
        case 'author_id':
            return $this->_vars['text_author_id'];
        case 'searchable_id':
            return $this->_vars['text_searchable_id'];
        case 'content_group':
            return $this->_vars['text_content_group'];
        case 'plugin':
            return $this->_vars['text_plugin'];
default:
return isset($this->_objects[$name]) ? $this->_objects[$name] : null;
        }
    }

    protected function _set($name, $value, $markDirty)
    {
        switch ($name) {
        case 'id':
            $this->_setVar('text_id', $value, $markDirty);
            break;
        case 'content_id':
            $this->_setVar('text_content_id', $value, $markDirty);
            break;
        case 'ctime':
            $this->_setVar('text_ctime', $value, $markDirty);
            break;
        case 'mtime':
            $this->_setVar('text_mtime', $value, $markDirty);
            break;
        case 'title':
            $this->_setVar('text_title', $value, $markDirty);
            break;
        case 'body':
            $this->_setVar('text_body', $value, $markDirty);
            break;
        case 'author_id':
            $this->_setVar('text_author_id', $value, $markDirty);
            break;
        case 'searchable_id':
            $this->_setVar('text_searchable_id', $value, $markDirty);
            break;
        case 'content_group':
            $this->_setVar('text_content_group', $value, $markDirty);
            break;
        case 'plugin':
            $this->_setVar('text_plugin', $value, $markDirty);
            break;
        }
    }

    protected function _initVar($name, $value)
    {
        switch ($name) {
        default:
            $this->_vars[$name] = $value;
            break;
        }
    }
}

abstract class Plugg_SimpleSearch_Model_Base_TextRepository extends Sabai_Model_EntityRepository
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Text', $model);
    }

    protected function _getCollectionByRowset(Sabai_DB_Rowset $rs)
    {
        return new Plugg_SimpleSearch_Model_Base_TextsByRowset($rs, $this->_model->create('Text'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Plugg_SimpleSearch_Model_Base_Texts($this->_model, $entities);
    }
}

class Plugg_SimpleSearch_Model_Base_TextsByRowset extends Sabai_Model_EntityCollection_Rowset
{
    public function __construct(Sabai_DB_Rowset $rs, Plugg_SimpleSearch_Model_Text $emptyEntity, Sabai_Model $model)
    {
        parent::__construct('Texts', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(Sabai_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Plugg_SimpleSearch_Model_Base_Texts extends Sabai_Model_EntityCollection_Array
{
    public function __construct(Sabai_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Texts', $entities);
    }
}