<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Aggregator_Model_Base_ItemCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'item_id',
        'created' => 'item_created',
        'updated' => 'item_updated',
        'title' => 'item_title',
        'url' => 'item_url',
        'body' => 'item_body',
        'author' => 'item_author',
        'authorLink' => 'item_author_link',
        'published' => 'item_published',
        'categories' => 'item_categories',
        'hidden' => 'item_hidden',
        'md5' => 'item_md5',
        'feedId' => 'item_feed_id',
    );
}