<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
plugins/HTMLPurifierFilter/Model/Customfilter.php
*/
abstract class Plugg_HTMLPurifierFilter_Model_Base_Customfilter extends Sabai_Model_Entity
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Customfilter', $model);
        $this->_vars = array('customfilter_id' => 0, 'customfilter_created' => 0, 'customfilter_updated' => 0, 'customfilter_name' => null, 'customfilter_plugin' => null, 'customfilter_order' => 0, 'customfilter_active' => 0);
    }

    public function __clone()
    {
        $this->_vars = array_merge($this->_vars, array('customfilter_id' => 0, 'customfilter_created' => 0, 'customfilter_updated' => 0));
    }

    public function __toString()
    {
        return 'Customfilter #' . $this->_get('id', null, null);
    }

    protected function _get($name, $sort, $order, $limit = 0, $offset = 0)
    {
        switch ($name) {
        case 'id':
            return $this->_vars['customfilter_id'];
        case 'created':
            return $this->_vars['customfilter_created'];
        case 'updated':
            return $this->_vars['customfilter_updated'];
        case 'name':
            return $this->_vars['customfilter_name'];
        case 'plugin':
            return $this->_vars['customfilter_plugin'];
        case 'order':
            return $this->_vars['customfilter_order'];
        case 'active':
            return $this->_vars['customfilter_active'];
default:
return isset($this->_objects[$name]) ? $this->_objects[$name] : null;
        }
    }

    protected function _set($name, $value, $markDirty)
    {
        switch ($name) {
        case 'id':
            $this->_setVar('customfilter_id', $value, $markDirty);
            break;
        case 'name':
            $this->_setVar('customfilter_name', $value, $markDirty);
            break;
        case 'plugin':
            $this->_setVar('customfilter_plugin', $value, $markDirty);
            break;
        case 'order':
            $this->_setVar('customfilter_order', $value, $markDirty);
            break;
        case 'active':
            $this->_setVar('customfilter_active', $value, $markDirty);
            break;
        }
    }

    protected function _initVar($name, $value)
    {
        switch ($name) {
        default:
            $this->_vars[$name] = $value;
            break;
        }
    }
}

abstract class Plugg_HTMLPurifierFilter_Model_Base_CustomfilterRepository extends Sabai_Model_EntityRepository
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Customfilter', $model);
    }

    protected function _getCollectionByRowset(Sabai_DB_Rowset $rs)
    {
        return new Plugg_HTMLPurifierFilter_Model_Base_CustomfiltersByRowset($rs, $this->_model->create('Customfilter'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Plugg_HTMLPurifierFilter_Model_Base_Customfilters($this->_model, $entities);
    }
}

class Plugg_HTMLPurifierFilter_Model_Base_CustomfiltersByRowset extends Sabai_Model_EntityCollection_Rowset
{
    public function __construct(Sabai_DB_Rowset $rs, Plugg_HTMLPurifierFilter_Model_Customfilter $emptyEntity, Sabai_Model $model)
    {
        parent::__construct('Customfilters', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(Sabai_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Plugg_HTMLPurifierFilter_Model_Base_Customfilters extends Sabai_Model_EntityCollection_Array
{
    public function __construct(Sabai_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Customfilters', $entities);
    }
}