<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Form_Model_Base_FieldCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'field_id',
        'created' => 'field_created',
        'updated' => 'field_updated',
        'type' => 'field_type',
        'plugin' => 'field_plugin',
        'system' => 'field_system',
    );
}