<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Form_Model_Base_FormCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'form_id',
        'created' => 'form_created',
        'updated' => 'form_updated',
        'title' => 'form_title',
        'header' => 'form_header',
        'headerFormatted' => 'form_header_formatted',
        'headerFormat' => 'form_header_format',
        'hidden' => 'form_hidden',
        'weight' => 'form_weight',
        'submitButtonLabel' => 'form_submit_button_label',
        'confirm' => 'form_confirm',
        'confirmButtonLabel' => 'form_confirm_button_label',
        'anonView' => 'form_anon_view',
        'anonSubmit' => 'form_anon_submit',
        'emailSettings' => 'form_email_settings',
        'formentryCount' => 'form_formentry_count',
        'formentryLast' => 'form_formentry_last',
        'formentryLasttime' => 'form_formentry_lasttime',
    );
}