<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
pluginsy/Friends/Model/FriendGateway.php
*/
abstract class Plugg_Friends_Model_Base_FriendGateway extends Sabai_Model_Gateway
{
    public function getName()
    {
        return 'friend';
    }

    public function getFields()
    {
        return array('friend_id' => Sabai_Model::KEY_TYPE_INT, 'friend_created' => Sabai_Model::KEY_TYPE_INT, 'friend_updated' => Sabai_Model::KEY_TYPE_INT, 'friend_with' => Sabai_Model::KEY_TYPE_INT, 'friend_relationships' => Sabai_Model::KEY_TYPE_VARCHAR, 'friend_user_id' => Sabai_Model::KEY_TYPE_INT);
    }

    protected function _getSelectByIdQuery($id, $fields)
    {
        return sprintf(
            'SELECT %s FROM %sfriend WHERE friend_id = %d',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $id
        );
    }

    protected function _getSelectByIdsQuery($ids, $fields)
    {
        return sprintf(
            'SELECT %s FROM %sfriend WHERE friend_id IN (%s)',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            implode(',', array_map('intval', $ids))
        );
    }

    protected function _getSelectByCriteriaQuery($criteriaStr, $fields)
    {
        return sprintf(
            'SELECT %1$s FROM %2$sfriend WHERE %3$s',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $criteriaStr
        );
    }

    protected function _getInsertQuery($values)
    {
        $values['friend_created'] = time();
        $values['friend_updated'] = 0;
        return sprintf("INSERT INTO %sfriend(friend_created, friend_updated, friend_with, friend_relationships, friend_user_id) VALUES(%d, %d, %d, %s, %d)", $this->_db->getResourcePrefix(), $values['friend_created'], $values['friend_updated'], $values['friend_with'], $this->_db->escapeString($values['friend_relationships']), $values['friend_user_id']);
    }

    protected function _getUpdateQuery($id, $values)
    {
        $last_update = $values['friend_updated'];
        $values['friend_updated'] = time();
        return sprintf("UPDATE %sfriend SET friend_updated = %d, friend_with = %d, friend_relationships = %s, friend_user_id = %d WHERE friend_id = %d AND friend_updated = %d", $this->_db->getResourcePrefix(), $values['friend_updated'], $values['friend_with'], $this->_db->escapeString($values['friend_relationships']), $values['friend_user_id'], $id, $last_update);
    }

    protected function _getDeleteQuery($id)
    {
        return sprintf('DELETE FROM %1$sfriend WHERE friend_id = %2$d', $this->_db->getResourcePrefix(), $id);
    }

    protected function _getUpdateByCriteriaQuery($criteriaStr, $sets)
    {
        $sets['friend_updated'] = 'friend_updated=' . time();
        return sprintf('UPDATE %sfriend SET %s WHERE %s', $this->_db->getResourcePrefix(), implode(',', $sets), $criteriaStr);
    }

    protected function _getDeleteByCriteriaQuery($criteriaStr)
    {
        return sprintf('DELETE FROM %1$sfriend WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    protected function _getCountByCriteriaQuery($criteriaStr)
    {
        return sprintf('SELECT COUNT(*) FROM %1$sfriend WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }
}