<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Friends_Model_Base_FriendCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'friend_id',
        'created' => 'friend_created',
        'updated' => 'friend_updated',
        'with' => 'friend_with',
        'relationships' => 'friend_relationships',
        'userId' => 'friend_user_id',
    );
}