<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
plugins/Friends/Model/Request.php
*/
abstract class Plugg_Friends_Model_Base_Request extends Sabai_Model_Entity
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Request', $model);
        $this->_vars = array('request_id' => 0, 'request_created' => 0, 'request_updated' => 0, 'request_to' => 0, 'request_message' => null, 'request_status' => 0, 'request_user_id' => 0);
    }

    public function __clone()
    {
        $this->_vars = array_merge($this->_vars, array('request_id' => 0, 'request_created' => 0, 'request_updated' => 0));
    }

    public function __toString()
    {
        return 'Request #' . $this->_get('id', null, null);
    }

    public function assignUser($user, $markDirty = true)
    {
        $this->_set('user_id', $user->id, $markDirty);
        return $this;
    }

    protected function _fetchUser($withData = false)
    {
        if (!isset($this->_objects['User'])) {
            $this->_objects['User'] = $this->_model->User_Identity($this->_vars['request_user_id'], $withData);
        }

        return $this->_objects['User'];
    }

    public function isOwnedBy($user)
    {
        return $this->user_id && $this->user_id == $user->id;
    }

    protected function _get($name, $sort, $order, $limit = 0, $offset = 0)
    {
        switch ($name) {
        case 'id':
            return $this->_vars['request_id'];
        case 'created':
            return $this->_vars['request_created'];
        case 'updated':
            return $this->_vars['request_updated'];
        case 'to':
            return $this->_vars['request_to'];
        case 'message':
            return $this->_vars['request_message'];
        case 'status':
            return $this->_vars['request_status'];
        case 'user_id':
            return $this->_vars['request_user_id'];
        case 'User':
            return $this->_fetchUser();
        case 'UserWithData':
            return $this->_fetchUser(true);
default:
return isset($this->_objects[$name]) ? $this->_objects[$name] : null;
        }
    }

    protected function _set($name, $value, $markDirty)
    {
        switch ($name) {
        case 'id':
            $this->_setVar('request_id', $value, $markDirty);
            break;
        case 'to':
            $this->_setVar('request_to', $value, $markDirty);
            break;
        case 'message':
            $this->_setVar('request_message', $value, $markDirty);
            break;
        case 'status':
            $this->_setVar('request_status', $value, $markDirty);
            break;
        case 'user_id':
            $this->_setVar('request_user_id', $value, $markDirty);
            break;
        }
    }

    protected function _initVar($name, $value)
    {
        switch ($name) {
        default:
            $this->_vars[$name] = $value;
            break;
        }
    }
}

abstract class Plugg_Friends_Model_Base_RequestRepository extends Sabai_Model_EntityRepository
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Request', $model);
    }

    public function fetchByUser($id, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeign('request_user_id', $id, $limit, $offset, $sort, $order);
    }

    public function paginateByUser($id, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntity('User', $id, $perpage, $sort, $order);
    }

    public function countByUser($id)
    {
        return $this->_countByForeign('request_user_id', $id);
    }

    public function fetchByUserAndCriteria($id, Sabai_Model_Criteria $criteria, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        return $this->_fetchByForeignAndCriteria('request_user_id', $id, $criteria, $limit, $offset, $sort, $order);
    }

    public function paginateByUserAndCriteria($id, Sabai_Model_Criteria $criteria, $perpage = 10, $sort = null, $order = null)
    {
        return $this->_paginateByEntityAndCriteria('User', $id, $criteria, $perpage, $sort, $order);
    }

    public function countByUserAndCriteria($id, Sabai_Model_Criteria $criteria)
    {
        return $this->_countByForeignAndCriteria('request_user_id', $id, $criteria);
    }

    protected function _getCollectionByRowset(Sabai_DB_Rowset $rs)
    {
        return new Plugg_Friends_Model_Base_RequestsByRowset($rs, $this->_model->create('Request'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Plugg_Friends_Model_Base_Requests($this->_model, $entities);
    }
}

class Plugg_Friends_Model_Base_RequestsByRowset extends Sabai_Model_EntityCollection_Rowset
{
    public function __construct(Sabai_DB_Rowset $rs, Plugg_Friends_Model_Request $emptyEntity, Sabai_Model $model)
    {
        parent::__construct('Requests', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(Sabai_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Plugg_Friends_Model_Base_Requests extends Sabai_Model_EntityCollection_Array
{
    public function __construct(Sabai_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Requests', $entities);
    }
}