<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_OpenIDAuth_Model_Base_AssocCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'assoc_id',
        'created' => 'assoc_created',
        'updated' => 'assoc_updated',
        'serverUrl' => 'assoc_server_url',
        'handle' => 'assoc_handle',
        'secret' => 'assoc_secret',
        'issued' => 'assoc_issued',
        'lifetime' => 'assoc_lifetime',
        'type' => 'assoc_type',
    );
}