<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_OpenIDAuth_Model_Base_NonceCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'nonce_id',
        'created' => 'nonce_created',
        'updated' => 'nonce_updated',
        'serverUrl' => 'nonce_server_url',
        'timestamp' => 'nonce_timestamp',
        'salt' => 'nonce_salt',
    );
}