<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Groups_Model_Base_ActivewidgetCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'activewidget_id',
        'created' => 'activewidget_created',
        'updated' => 'activewidget_updated',
        'title' => 'activewidget_title',
        'order' => 'activewidget_order',
        'position' => 'activewidget_position',
        'settings' => 'activewidget_settings',
        'cache' => 'activewidget_cache',
        'cacheTime' => 'activewidget_cache_time',
        'cacheLifetime' => 'activewidget_cache_lifetime',
        'widgetId' => 'activewidget_widget_id',
        'groupId' => 'activewidget_group_id',
    );
}