<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Locale_Model_Base_MessageCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'message_id',
        'created' => 'message_created',
        'updated' => 'message_updated',
        'key' => 'message_key',
        'lang' => 'message_lang',
        'localized' => 'message_localized',
        'plugin' => 'message_plugin',
    );
}