<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
plugins/Locale/Model/Message.php
*/
abstract class Plugg_Locale_Model_Base_Message extends Sabai_Model_Entity
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Message', $model);
        $this->_vars = array('message_id' => 0, 'message_created' => 0, 'message_updated' => 0, 'message_key' => null, 'message_lang' => null, 'message_localized' => null, 'message_plugin' => null);
    }

    public function __clone()
    {
        $this->_vars = array_merge($this->_vars, array('message_id' => 0, 'message_created' => 0, 'message_updated' => 0));
    }

    public function __toString()
    {
        return $this->_get('key', null, null);
    }

    protected function _get($name, $sort, $order, $limit = 0, $offset = 0)
    {
        switch ($name) {
        case 'id':
            return $this->_vars['message_id'];
        case 'created':
            return $this->_vars['message_created'];
        case 'updated':
            return $this->_vars['message_updated'];
        case 'key':
            return $this->_vars['message_key'];
        case 'lang':
            return $this->_vars['message_lang'];
        case 'localized':
            return $this->_vars['message_localized'];
        case 'plugin':
            return $this->_vars['message_plugin'];
default:
return isset($this->_objects[$name]) ? $this->_objects[$name] : null;
        }
    }

    protected function _set($name, $value, $markDirty)
    {
        switch ($name) {
        case 'id':
            $this->_setVar('message_id', $value, $markDirty);
            break;
        case 'key':
            $this->_setVar('message_key', $value, $markDirty);
            break;
        case 'lang':
            $this->_setVar('message_lang', $value, $markDirty);
            break;
        case 'localized':
            $this->_setVar('message_localized', $value, $markDirty);
            break;
        case 'plugin':
            $this->_setVar('message_plugin', $value, $markDirty);
            break;
        }
    }

    protected function _initVar($name, $value)
    {
        switch ($name) {
        default:
            $this->_vars[$name] = $value;
            break;
        }
    }
}

abstract class Plugg_Locale_Model_Base_MessageRepository extends Sabai_Model_EntityRepository
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Message', $model);
    }

    protected function _getCollectionByRowset(Sabai_DB_Rowset $rs)
    {
        return new Plugg_Locale_Model_Base_MessagesByRowset($rs, $this->_model->create('Message'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Plugg_Locale_Model_Base_Messages($this->_model, $entities);
    }
}

class Plugg_Locale_Model_Base_MessagesByRowset extends Sabai_Model_EntityCollection_Rowset
{
    public function __construct(Sabai_DB_Rowset $rs, Plugg_Locale_Model_Message $emptyEntity, Sabai_Model $model)
    {
        parent::__construct('Messages', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(Sabai_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Plugg_Locale_Model_Base_Messages extends Sabai_Model_EntityCollection_Array
{
    public function __construct(Sabai_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Messages', $entities);
    }
}