<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_User_Model_Base_AuthdataCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'authdata_id',
        'created' => 'authdata_created',
        'updated' => 'authdata_updated',
        'claimedId' => 'authdata_claimed_id',
        'displayId' => 'authdata_display_id',
        'lastused' => 'authdata_lastused',
        'authId' => 'authdata_auth_id',
        'userId' => 'authdata_user_id',
    );
}