<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_User_Model_Base_AuthCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'auth_id',
        'created' => 'auth_created',
        'updated' => 'auth_updated',
        'name' => 'auth_name',
        'title' => 'auth_title',
        'plugin' => 'auth_plugin',
        'order' => 'auth_order',
        'active' => 'auth_active',
        'authdataCount' => 'auth_authdata_count',
        'authdataLast' => 'auth_authdata_last',
        'authdataLasttime' => 'auth_authdata_lasttime',
    );
}