<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_User_Model_Base_FieldCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'field_id',
        'created' => 'field_created',
        'updated' => 'field_updated',
        'name' => 'field_name',
        'title' => 'field_title',
        'description' => 'field_description',
        'weight' => 'field_weight',
        'required' => 'field_required',
        'collapsible' => 'field_collapsible',
        'collapsed' => 'field_collapsed',
        'settings' => 'field_settings',
        'fieldset' => 'field_fieldset',
        'fieldId' => 'field_field_id',
        'registerable' => 'field_registerable',
        'editable' => 'field_editable',
        'visibilityDefault' => 'field_visibility_default',
        'visibilityControl' => 'field_visibility_control',
    );
}