<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_User_Model_Base_MemberCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'member_id',
        'created' => 'member_created',
        'updated' => 'member_updated',
        'roleId' => 'member_role_id',
        'userId' => 'member_user_id',
    );
}