<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_User_Model_Base_MetaCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'meta_id',
        'created' => 'meta_created',
        'updated' => 'meta_updated',
        'key' => 'meta_key',
        'value' => 'meta_value',
        'serialized' => 'meta_serialized',
        'userId' => 'meta_user_id',
    );
}