<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
plugins/User/Model/Queue.php
*/
abstract class Plugg_User_Model_Base_Queue extends Sabai_Model_Entity
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Queue', $model);
        $this->_vars = array('queue_id' => 0, 'queue_created' => 0, 'queue_updated' => 0, 'queue_data' => null, 'queue_key' => null, 'queue_type' => 0, 'queue_notify_email' => null, 'queue_identity_id' => null, 'queue_auth_data' => null, 'queue_extra_data' => null, 'queue_register_username' => null);
    }

    public function __clone()
    {
        $this->_vars = array_merge($this->_vars, array('queue_id' => 0, 'queue_created' => 0, 'queue_updated' => 0));
    }

    public function __toString()
    {
        return 'Queue #' . $this->_get('id', null, null);
    }

    protected function _get($name, $sort, $order, $limit = 0, $offset = 0)
    {
        switch ($name) {
        case 'id':
            return $this->_vars['queue_id'];
        case 'created':
            return $this->_vars['queue_created'];
        case 'updated':
            return $this->_vars['queue_updated'];
        case 'data':
            return $this->_vars['queue_data'];
        case 'key':
            return $this->_vars['queue_key'];
        case 'type':
            return $this->_vars['queue_type'];
        case 'notify_email':
            return $this->_vars['queue_notify_email'];
        case 'identity_id':
            return $this->_vars['queue_identity_id'];
        case 'auth_data':
            return $this->_vars['queue_auth_data'];
        case 'extra_data':
            return $this->_vars['queue_extra_data'];
        case 'register_username':
            return $this->_vars['queue_register_username'];
default:
return isset($this->_objects[$name]) ? $this->_objects[$name] : null;
        }
    }

    protected function _set($name, $value, $markDirty)
    {
        switch ($name) {
        case 'id':
            $this->_setVar('queue_id', $value, $markDirty);
            break;
        case 'data':
            $this->_setVar('queue_data', $value, $markDirty);
            break;
        case 'key':
            $this->_setVar('queue_key', $value, $markDirty);
            break;
        case 'type':
            $this->_setVar('queue_type', $value, $markDirty);
            break;
        case 'notify_email':
            $this->_setVar('queue_notify_email', $value, $markDirty);
            break;
        case 'identity_id':
            $this->_setVar('queue_identity_id', $value, $markDirty);
            break;
        case 'auth_data':
            $this->_setVar('queue_auth_data', $value, $markDirty);
            break;
        case 'extra_data':
            $this->_setVar('queue_extra_data', $value, $markDirty);
            break;
        case 'register_username':
            $this->_setVar('queue_register_username', $value, $markDirty);
            break;
        }
    }

    protected function _initVar($name, $value)
    {
        switch ($name) {
        default:
            $this->_vars[$name] = $value;
            break;
        }
    }
}

abstract class Plugg_User_Model_Base_QueueRepository extends Sabai_Model_EntityRepository
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Queue', $model);
    }

    protected function _getCollectionByRowset(Sabai_DB_Rowset $rs)
    {
        return new Plugg_User_Model_Base_QueuesByRowset($rs, $this->_model->create('Queue'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Plugg_User_Model_Base_Queues($this->_model, $entities);
    }
}

class Plugg_User_Model_Base_QueuesByRowset extends Sabai_Model_EntityCollection_Rowset
{
    public function __construct(Sabai_DB_Rowset $rs, Plugg_User_Model_Queue $emptyEntity, Sabai_Model $model)
    {
        parent::__construct('Queues', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(Sabai_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Plugg_User_Model_Base_Queues extends Sabai_Model_EntityCollection_Array
{
    public function __construct(Sabai_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Queues', $entities);
    }
}