<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_User_Model_Base_QueueCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'queue_id',
        'created' => 'queue_created',
        'updated' => 'queue_updated',
        'data' => 'queue_data',
        'key' => 'queue_key',
        'type' => 'queue_type',
        'notifyEmail' => 'queue_notify_email',
        'identityId' => 'queue_identity_id',
        'authData' => 'queue_auth_data',
        'extraData' => 'queue_extra_data',
        'registerUsername' => 'queue_register_username',
    );
}