<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
pluginsy/User/Model/StatGateway.php
*/
abstract class Plugg_User_Model_Base_StatGateway extends Sabai_Model_Gateway
{
    public function getName()
    {
        return 'stat';
    }

    public function getFields()
    {
        return array('stat_id' => Sabai_Model::KEY_TYPE_INT, 'stat_created' => Sabai_Model::KEY_TYPE_INT, 'stat_updated' => Sabai_Model::KEY_TYPE_INT, 'stat_last_login' => Sabai_Model::KEY_TYPE_INT, 'stat_last_edit' => Sabai_Model::KEY_TYPE_INT, 'stat_last_edit_email' => Sabai_Model::KEY_TYPE_INT, 'stat_last_edit_password' => Sabai_Model::KEY_TYPE_INT, 'stat_last_edit_image' => Sabai_Model::KEY_TYPE_INT, 'stat_user_id' => Sabai_Model::KEY_TYPE_INT);
    }

    protected function _getSelectByIdQuery($id, $fields)
    {
        return sprintf(
            'SELECT %s FROM %sstat WHERE stat_id = %d',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $id
        );
    }

    protected function _getSelectByIdsQuery($ids, $fields)
    {
        return sprintf(
            'SELECT %s FROM %sstat WHERE stat_id IN (%s)',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            implode(',', array_map('intval', $ids))
        );
    }

    protected function _getSelectByCriteriaQuery($criteriaStr, $fields)
    {
        return sprintf(
            'SELECT %1$s FROM %2$sstat WHERE %3$s',
            empty($fields) ? '*' : implode(', ', $fields),
            $this->_db->getResourcePrefix(),
            $criteriaStr
        );
    }

    protected function _getInsertQuery($values)
    {
        $values['stat_created'] = time();
        $values['stat_updated'] = 0;
        return sprintf("INSERT INTO %sstat(stat_created, stat_updated, stat_last_login, stat_last_edit, stat_last_edit_email, stat_last_edit_password, stat_last_edit_image, stat_user_id) VALUES(%d, %d, %d, %d, %d, %d, %d, %d)", $this->_db->getResourcePrefix(), $values['stat_created'], $values['stat_updated'], $values['stat_last_login'], $values['stat_last_edit'], $values['stat_last_edit_email'], $values['stat_last_edit_password'], $values['stat_last_edit_image'], $values['stat_user_id']);
    }

    protected function _getUpdateQuery($id, $values)
    {
        $last_update = $values['stat_updated'];
        $values['stat_updated'] = time();
        return sprintf("UPDATE %sstat SET stat_updated = %d, stat_last_login = %d, stat_last_edit = %d, stat_last_edit_email = %d, stat_last_edit_password = %d, stat_last_edit_image = %d, stat_user_id = %d WHERE stat_id = %d AND stat_updated = %d", $this->_db->getResourcePrefix(), $values['stat_updated'], $values['stat_last_login'], $values['stat_last_edit'], $values['stat_last_edit_email'], $values['stat_last_edit_password'], $values['stat_last_edit_image'], $values['stat_user_id'], $id, $last_update);
    }

    protected function _getDeleteQuery($id)
    {
        return sprintf('DELETE FROM %1$sstat WHERE stat_id = %2$d', $this->_db->getResourcePrefix(), $id);
    }

    protected function _getUpdateByCriteriaQuery($criteriaStr, $sets)
    {
        $sets['stat_updated'] = 'stat_updated=' . time();
        return sprintf('UPDATE %sstat SET %s WHERE %s', $this->_db->getResourcePrefix(), implode(',', $sets), $criteriaStr);
    }

    protected function _getDeleteByCriteriaQuery($criteriaStr)
    {
        return sprintf('DELETE FROM %1$sstat WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    protected function _getCountByCriteriaQuery($criteriaStr)
    {
        return sprintf('SELECT COUNT(*) FROM %1$sstat WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }
}