<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_User_Model_Base_StatCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'stat_id',
        'created' => 'stat_created',
        'updated' => 'stat_updated',
        'lastLogin' => 'stat_last_login',
        'lastEdit' => 'stat_last_edit',
        'lastEditEmail' => 'stat_last_edit_email',
        'lastEditPassword' => 'stat_last_edit_password',
        'lastEditImage' => 'stat_last_edit_image',
        'userId' => 'stat_user_id',
    );
}