<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_User_Model_Base_StatusCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'status_id',
        'created' => 'status_created',
        'updated' => 'status_updated',
        'text' => 'status_text',
        'textFiltered' => 'status_text_filtered',
        'textFilterId' => 'status_text_filter_id',
        'userId' => 'status_user_id',
    );
}