<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
plugins/XOOPSCube/Model/Block.php
*/
abstract class Plugg_XOOPSCube_Model_Base_Block extends Sabai_Model_Entity
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Block', $model);
        $this->_vars = array('block_id' => 0, 'block_created' => 0, 'block_updated' => 0, 'block_plugin' => null, 'block_widget' => null, 'block_block_id' => 0);
    }

    public function __clone()
    {
        $this->_vars = array_merge($this->_vars, array('block_id' => 0, 'block_created' => 0, 'block_updated' => 0));
    }

    public function __toString()
    {
        return 'Block #' . $this->_get('id', null, null);
    }

    protected function _get($name, $sort, $order, $limit = 0, $offset = 0)
    {
        switch ($name) {
        case 'id':
            return $this->_vars['block_id'];
        case 'created':
            return $this->_vars['block_created'];
        case 'updated':
            return $this->_vars['block_updated'];
        case 'plugin':
            return $this->_vars['block_plugin'];
        case 'widget':
            return $this->_vars['block_widget'];
        case 'block_id':
            return $this->_vars['block_block_id'];
default:
return isset($this->_objects[$name]) ? $this->_objects[$name] : null;
        }
    }

    protected function _set($name, $value, $markDirty)
    {
        switch ($name) {
        case 'id':
            $this->_setVar('block_id', $value, $markDirty);
            break;
        case 'plugin':
            $this->_setVar('block_plugin', $value, $markDirty);
            break;
        case 'widget':
            $this->_setVar('block_widget', $value, $markDirty);
            break;
        case 'block_id':
            $this->_setVar('block_block_id', $value, $markDirty);
            break;
        }
    }

    protected function _initVar($name, $value)
    {
        switch ($name) {
        default:
            $this->_vars[$name] = $value;
            break;
        }
    }
}

abstract class Plugg_XOOPSCube_Model_Base_BlockRepository extends Sabai_Model_EntityRepository
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Block', $model);
    }

    protected function _getCollectionByRowset(Sabai_DB_Rowset $rs)
    {
        return new Plugg_XOOPSCube_Model_Base_BlocksByRowset($rs, $this->_model->create('Block'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Plugg_XOOPSCube_Model_Base_Blocks($this->_model, $entities);
    }
}

class Plugg_XOOPSCube_Model_Base_BlocksByRowset extends Sabai_Model_EntityCollection_Rowset
{
    public function __construct(Sabai_DB_Rowset $rs, Plugg_XOOPSCube_Model_Block $emptyEntity, Sabai_Model $model)
    {
        parent::__construct('Blocks', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(Sabai_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Plugg_XOOPSCube_Model_Base_Blocks extends Sabai_Model_EntityCollection_Array
{
    public function __construct(Sabai_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Blocks', $entities);
    }
}