<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_XOOPSCube_Model_Base_SearchCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'search_id',
        'created' => 'search_created',
        'updated' => 'search_updated',
        'module' => 'search_module',
        'name' => 'search_name',
        'urlFormat' => 'search_url_format',
    );
}