<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
plugins/XOOPSCube/Model/Search.php
*/
abstract class Plugg_XOOPSCube_Model_Base_Search extends Sabai_Model_Entity
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Search', $model);
        $this->_vars = array('search_id' => 0, 'search_created' => 0, 'search_updated' => 0, 'search_module' => null, 'search_name' => null, 'search_url_format' => null);
    }

    public function __clone()
    {
        $this->_vars = array_merge($this->_vars, array('search_id' => 0, 'search_created' => 0, 'search_updated' => 0));
    }

    public function __toString()
    {
        return 'Search #' . $this->_get('id', null, null);
    }

    protected function _get($name, $sort, $order, $limit = 0, $offset = 0)
    {
        switch ($name) {
        case 'id':
            return $this->_vars['search_id'];
        case 'created':
            return $this->_vars['search_created'];
        case 'updated':
            return $this->_vars['search_updated'];
        case 'module':
            return $this->_vars['search_module'];
        case 'name':
            return $this->_vars['search_name'];
        case 'url_format':
            return $this->_vars['search_url_format'];
default:
return isset($this->_objects[$name]) ? $this->_objects[$name] : null;
        }
    }

    protected function _set($name, $value, $markDirty)
    {
        switch ($name) {
        case 'id':
            $this->_setVar('search_id', $value, $markDirty);
            break;
        case 'module':
            $this->_setVar('search_module', $value, $markDirty);
            break;
        case 'name':
            $this->_setVar('search_name', $value, $markDirty);
            break;
        case 'url_format':
            $this->_setVar('search_url_format', $value, $markDirty);
            break;
        }
    }

    protected function _initVar($name, $value)
    {
        switch ($name) {
        default:
            $this->_vars[$name] = $value;
            break;
        }
    }
}

abstract class Plugg_XOOPSCube_Model_Base_SearchRepository extends Sabai_Model_EntityRepository
{
    public function __construct(Sabai_Model $model)
    {
        parent::__construct('Search', $model);
    }

    protected function _getCollectionByRowset(Sabai_DB_Rowset $rs)
    {
        return new Plugg_XOOPSCube_Model_Base_SearchsByRowset($rs, $this->_model->create('Search'), $this->_model);
    }

    public function createCollection(array $entities = array())
    {
        return new Plugg_XOOPSCube_Model_Base_Searchs($this->_model, $entities);
    }
}

class Plugg_XOOPSCube_Model_Base_SearchsByRowset extends Sabai_Model_EntityCollection_Rowset
{
    public function __construct(Sabai_DB_Rowset $rs, Plugg_XOOPSCube_Model_Search $emptyEntity, Sabai_Model $model)
    {
        parent::__construct('Searchs', $rs, $emptyEntity, $model);
    }

    protected function _loadRow(Sabai_Model_Entity $entity, array $row)
    {
        $entity->initVars($row);
    }
}

class Plugg_XOOPSCube_Model_Base_Searchs extends Sabai_Model_EntityCollection_Array
{
    public function __construct(Sabai_Model $model, array $entities = array())
    {
        parent::__construct($model, 'Searchs', $entities);
    }
}