<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Filters_Model_Base_FilterCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'filter_id',
        'created' => 'filter_created',
        'updated' => 'filter_updated',
        'name' => 'filter_name',
        'plugin' => 'filter_plugin',
        'title' => 'filter_title',
        'order' => 'filter_order',
        'active' => 'filter_active',
    );
}