<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Search_Model_Base_EngineCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'engine_id',
        'created' => 'engine_created',
        'updated' => 'engine_updated',
        'plugin' => 'engine_plugin',
    );
}