<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

class Plugg_Search_Model_Base_Searchable2engineCriteria extends Sabai_Model_EntityCriteria
{
    var $_keys = array(
        'id' => 'searchable2engine_id',
        'created' => 'searchable2engine_created',
        'updated' => 'searchable2engine_updated',
        'searchableId' => 'searchable2engine_searchable_id',
        'engineId' => 'searchable2engine_engine_id',
    );
}